---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - fs.go-faster.org
  resources:
  - fsaccesskeys
  - fsbuckets
  - fsclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fs.go-faster.org
  resources:
  - fsaccesskeys/finalizers
  - fsbuckets/finalizers
  - fsclusters/finalizers
  verbs:
  - update
- apiGroups:
  - fs.go-faster.org
  resources:
  - fsaccesskeys/status
  - fsbuckets/status
  - fsclusters/status
  verbs:
  - get
  - patch
  - update
