apiVersion: fs.go-faster.org/v1alpha1
kind: FSCluster
metadata:
  labels:
    app.kubernetes.io/name: fs-operator
    app.kubernetes.io/managed-by: kustomize
  name: fscluster-sample
spec:
  # TODO(user): Add fields here
