apiVersion: fs.go-faster.org/v1alpha1
kind: FSAccessKey
metadata:
  labels:
    app.kubernetes.io/name: fs-operator
    app.kubernetes.io/managed-by: kustomize
  name: fsaccesskey-sample
spec:
  clusterRef:
    name: fscluster-sample
  grants:
    - bucket: "fsbucket-sample"
      permission: write
